target 'Segment-MoEngage_Example' do
  use_frameworks!

  pod 'Segment-MoEngage', :path => '../'
  pod 'MoEngageInApp'

  target 'Segment-MoEngage_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end

end



target 'NotificationService' do
use_frameworks!
 pod 'MoEngageRichNotification'
end


target 'NotificationContent' do
  use_frameworks!
 pod 'MoEngageRichNotification'
end
