target 'Segment-MoEngage_Example' do
  use_frameworks!
  pod 'Segment-MoEngage', :path => '../'

  target 'Segment-MoEngage_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
